# Generated by Django 3.2 on 2023-05-09 11:51

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует'}, help_text='Введите юзернейм пользователя. Максимум 150 символов. Используйте только английские буквы, цифры и символы @/./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='юзернейм пользователя'),
        ),
    ]
