# Generated by Django 3.2 on 2023-05-10 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230509_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, message='Укажите время больше либо равное 1')], verbose_name='Время приготовления в минутах'),
            preserve_default=False,
        ),
    ]
